import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/contexts/QueryProvider";


const outfit = Outfit({ subsets: ['latin'], weight: ["300", "400", "500"] })

export const metadata: Metadata = {
    title: "SuperXBoss",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body   cz-shortcut-listen="true" className={`${outfit.className} antialiased text-gray-700`}>
                <QueryProvider>
                        {children}
                </QueryProvider>
            </body>
        </html>
    );
}
